--- 
title: "Forestry 472: Ecological Monitoring and Data Analysis"
author: "Andrew O. Finley and Jeffrey W. Doser"
date: "`r Sys.Date()`"
documentclass: krantz
bibliography: [text.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
always_allow_html: yes
lot: yes
lof: yes
site: bookdown::bookdown_site
description: "Course book for FOR472: Ecological Monitoring and Data Analysis"
graphics: yes
header-includes:
  - \usepackage{color}
  - \usepackage{graphicx}
  - \graphicspath{{_bookdown_files/}}
---

```{r setup, include=FALSE}
library(tidyr)
library(knitr)
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4,
  formatR.arrow = TRUE
)
opts_chunk$set(comment=NA, tidy=TRUE, prompt=TRUE)

# install the packages needed by this book; you fill out c(), e.g. c('ggplot2', 'dplyr')
lapply(c('xfun'), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})
```

# Preface {-}

This text is an introduction to data sciences for Forestry and Environmental students. Understanding and responding to current environmental challenges requires strong quantitative and analytical skills. There is a pressing need for professionals with data science expertise in this data rich era. The [McKinsey Global Institute](http://www.mckinsey.com/insights/business_technology/big_data_the_next_frontier_for_innovation) predicts that "by 2018, the United States alone could face a shortage of 140,000 to 190,000 people with deep analytical skills as well as 1.5 million managers and analysts with the know-how to use the analysis of big data to make effective decisions". The Harvard Business Review dubbed *data scientist* ["The Sexiest Job of the 21st Century"](https://hbr.org/2012/10/data-scientist-the-sexiest-job-of-the-21st-century). This need is not at all confined to the tech sector, as forestry professionals are increasingly asked to assume the role of *data scientists* and *data analysts* given the rapid accumulation and availability of environmental data (see, e.g. @Schimel2015). [Thomson Nguyen's talk](www.import.io/post/data-scientists-vs-data-analysts-why-the-distinction-matters) on the difference between a data scientist and a data analyst is very interesting and contains elements relevant to the aim of this text. This aim is to give you the opportunity to acquire the tools needed to become an environmental data analyst. Following @Bravo16 a *data analyst* has the ability to make appropriate calculations, convert data to graphical representation, interpret the information presented in graphical or mathematical forms, and make judgements or draw conclusions based on the quantitative analysis of data. 

